apiVersion: apps/v1
kind: Deployment
metadata:
  name: RD0105
spec: # Defines the Deployment Behaviour
  replicas: 3
  selector:
    matchLabels:
      app: RDapp
  template:
    metadata:
      labels:
        app: RDapp
    spec: # Define the Pod behaviour
      containers:
      - name: RDapp-container
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
          requests:
            memory: "128Mb"
            cpu: "50m"
        ports:
        - containerPort: 3015
