apiVersion: apps/v1
kind: Deployment
metadata:
  name: rd0105
spec: # Defines the Deployment Behaviour
  replicas: 3
  selector:
    matchLabels:
      app: rdev
  template:
    metadata:
      labels:
        app: rdev
    spec: # Define the Pod behaviour
      containers:
      - name: rdapp-container
        image: muralisocial123/flower-app:1.0
        resources:
          limits:
            memory: "250Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3015
---
# Writing Service.yml to expose the application
appVersion: v1
kind: service
metadata:
  name: rd0105
spec:
  selector:
    app: rd0105
ports:
  port: 3016 # Service Port
  targetPort: 3015 # Container Port
type: LoadBalancer